---
abstract: 'Access to Mediathek'
author:
  - 'Robin Clarke <perl@robinclarke.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TV-Mediathek
no_index:
  directory:
    - t
    - inc
requires:
  Class::Date: 0
  DBD::SQLite: 0
  DBI: 0
  Data::Dumper: 0
  Encode: 0
  ExtUtils::MakeMaker: 0
  File::HomeDir: 0
  File::Spec::Functions: 0
  File::Util: 0
  Format::Human::Bytes: 0
  Getopt::Long: 0
  IO::Uncompress::AnyUncompress: 0
  Lingua::DE::ASCII: 0
  Log::Log4perl: 0
  Moose: 0
  MooseX::Log::Log4perl: 0
  Pod::Usage: 0
  Test::More: 0
  Video::Flvstreamer: 0.03
  WWW::Mechanize: 0
  XML::Twig: 0
  YAML::Any: 0
resources:
  bugtracker: https://github.com/robin13/mediathekp/issues
  homepage: https://github.com/robin13/mediathekp
  repository: https://github.com/robin13/mediathekp
version: 0.02
